#debug: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tc-jpa-study
    username: root
    password: password
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        format_sql: true
        dialect:
          storage_engine: innodb
    hibernate:
      ddl-auto: create
    show-sql: true
